name: Pull, build docker image and push to repository
on: 
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true
    outputs:
      image:
        description: URL for docker image with tag
        value: ${{ jobs.build.outputs.image }}
jobs:        
  build:
    runs-on: ubuntu-latest
    outputs:
      image: '${{ steps.docker_build.outputs.imageFullName }}:${{ steps.docker_build.outputs.tags }}'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
      - name: Build and push
        id: docker_build
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: kuboard-cicd-test
          registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}