name: Pull, build docker image and push to repository
on: 
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true
    outputs:
      image:
        description: URL for docker image with tag
        value: ${{ jobs.build.outputs.image }}
jobs:        
  build:
    runs-on: ubuntu-latest
    outputs:
      image: '${{ steps.docker_build.outputs.imageFullName }}:${{ steps.docker_build.outputs.tags }}'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore  the failure of a step and avoid terminating the job.
        continue-on-error: true
        # https://github.com/jlumbroso/free-disk-space/issues/14
      - name: Update Package List and Remove Dotnet
        run: |
          sudo apt-get update
          sudo apt-get remove -y '^dotnet-.*'
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
          
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - name: Build and push
        id: docker_build
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: guomaoqiu/kuboard-cicd-test
          registry: docker.io
          addTimestamp: true
          username: guomaoqiu
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: x
        run: echo '${{ steps.docker_build.outputs.imageFullName }}:${{ steps.docker_build.outputs.tags }}'
