name: Pull, build docker image and push to repository
on: 
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true
    outputs:
      image:
        description: URL for docker image with tag
        value: ${{ jobs.build.outputs.image }}
jobs:        
  build:
    runs-on: ubuntu-latest
    outputs:
      image: '${{ steps.docker_build.outputs.imageFullName }}:${{ steps.docker_build.outputs.tags }}'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build and push Docker image
        id: docker_build
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: guomaoqiu/kuboard-cicd-test
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          dockerfile: Dockerfile
          buildArgs: |
            ARG PYTHON_VERSION=3.9.6
          tags: |
            latest
            ${{ github.sha }}
          push: true