name: Deploy to staging
on: 
  push:
    branches:
      # - develop
      - staging
    tags:
      - staging
      - '*-rc*'
jobs:
  build:
    uses: ./.github/workflows/build.yml 
    secrets: inherit
  deploy-update:
    needs: build
    strategy:
      matrix:
        workload: [kuboard-cicd-test01, kuboard-cicd-test02, kuboard-cicd-test03]
    uses: ./.github/workflows/update-image.yml 
    with:
      k8s-namespace: staging
      k8s-workload: ${{ matrix.workload }}
      image: ${{ needs.build.outputs.image }}
    secrets: inherit
