name: Update K8S workload image
on: 
  workflow_call:
    inputs:
      image_name: 
        required: true
        type: string
      image_tag: 
        required: true
        type: string
      k8s-namespace:
        required: true
        type: string
      k8s-workload:
        required: true
        type: string
    secrets:
      KUBOARD_USERNAME:
        required: true
      KUBOARD_ACCESS_KEY:
        required: true
      KUBOARD_API_URL:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print image name
        run: echo ${{ inputs.image }}
      - name: Update image on K8S
        id: http-request
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.KUBOARD_API_URL }}/cluster/ckb/kind/CICDApi/ops/resource/updateImageTag
          method: 'PUT'
          customHeaders: '{"Content-Type": "application/json", "Cookie": "KuboardUsername=${{ secrets.KUBOARD_USERNAME }}; KuboardAccessKey=${{ secrets.KUBOARD_ACCESS_KEY }}"}'
          data: '{"kind":"deployments","namespace":"${{ inputs.k8s-namespace }}","name":"${{ inputs.k8s-workload }}","images":{"${{ inputs.k8s-workload }}":"${{ inputs.image }}":"${{ inputs.image_tag }}"}}'
      - name: Display Response
        run: |
            echo "Response response: ${{ steps.http-request.outputs.response }}"
            echo "Response headers: ${{ steps.http-request.outputs.headers }}"
            echo "Response status code: ${{ steps.http-request.outputs.status_code }}"
            echo "Response body: ${{ steps.http-request.outputs.body }}"
      # - name: Restart container
      #   uses: fjogeleit/http-request-action@v1
      #   with:
      #     url: ${{ secrets.KUBOARD_API_URL }}/cluster/ckb/kind/CICDApi/ops/resource/restartWorkload
      #     method: 'PUT'
      #     customHeaders: '{"Content-Type": "application/json", "Cookie": "KuboardUsername=${{ secrets.KUBOARD_USERNAME }}; KuboardAccessKey=${{ secrets.KUBOARD_ACCESS_KEY }}"}'
      #     data: '{"kind":"deployments","namespace":"${{ inputs.k8s-namespace }}","name":"${{ inputs.k8s-workload }}"}'


